# Generated by Django 5.2 on 2025-04-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='pdf/'),
        ),
    ]
